project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"

execute:
  freeze: auto

website:
  title: "TopOpt.jl Tutorials"
  navbar:
    background: light
    logo: logo.png
    logo-alt: "TopOpt.jl Logo"
    title: "TopOpt.jl Tutorials"
    right:
      - text: "Documentation"
        href: "../index.html"
        icon: book

format:
  html:
    toc: true
    toc-location: left
    css: topopt-tutorials.css
    embed-resources: false
