project:
  type: website
  output-dir: _site

execute:
  enabled: false

website:
  title: "TopOpt.jl"
  image: "../../assets/logo.png"
  sidebar:
    style: "docked"
    background: light
    logo: "../../assets/logo.png"
  navbar:
    logo: "../../assets/logo.png"
    right:
      - text: "Back to Docs"
        href: "../index.html"
      - icon: github
        href: "https://github.com/JuliaTopOpt/TopOpt.jl"

format:
  html:
    toc: true
    toc-location: right
    toc-floating: true
    embed-resources: true
    self-contained-math: true
