# Compare the OpenLSTO Julia port against the reference C++ OpenLSTO output.
#
# The reference (test/OpenLSTO/reference_40x20.txt) is generated by
# `compliance_driver.cpp`, which reproduces the OpenLSTO compliance problem on
# a 40x20 cantilever with a 3x3 grid of radius-2 holes. The level-set method
# is chaotic in the sense that tiny floating-point differences (the CG solver,
# least-squares solve) accumulate into growing trajectory differences after a
# few iterations, so the first iteration is compared tightly and the final
# result loosely.

using Test
using LinearAlgebra, SparseArrays, Random
using TopOpt

const L = TopOpt.OpenLSTO

const HOLES = L.LevelSetHole[
    L.LevelSetHole(8, 4, 2),
    L.LevelSetHole(16, 4, 2),
    L.LevelSetHole(24, 4, 2),
    L.LevelSetHole(12, 8, 2),
    L.LevelSetHole(20, 8, 2),
    L.LevelSetHole(28, 8, 2),
    L.LevelSetHole(8, 12, 2),
    L.LevelSetHole(16, 12, 2),
    L.LevelSetHole(24, 12, 2),
]

function read_reference(path::AbstractString)
    iterations = Int[]
    compliances = Float64[]
    areas = Float64[]
    for line in eachline(path)
        tokens = split(line)
        length(tokens) == 3 || continue
        push!(iterations, parse(Int, tokens[1]))
        push!(compliances, parse(Float64, tokens[2]))
        push!(areas, parse(Float64, tokens[3]))
    end
    return iterations, compliances, areas
end

@testset "OpenLSTO compliance reference" begin
    reference = get(ENV, "OPENLSTO_REFERENCE", joinpath(@__DIR__, "reference_40x20.txt"))
    ref_iters, ref_compliance, ref_area = read_reference(reference)
    @test !isempty(ref_iters)

    result = L.compliance_minimization(;
        nelx=40, nely=20, holes=HOLES, max_iterations=length(ref_iters), verbose=false
    )

    @test length(result.objectives) == length(ref_iters)
    @test length(result.areas) == length(ref_iters)

    # The first iteration is deterministic: it only depends on the initial
    # level set, which the port reproduces to machine precision.
    @test result.objectives[1] ≈ ref_compliance[1] rtol = 1e-6
    @test result.areas[1] ≈ ref_area[1] atol = 1e-8

    # After many iterations the two trajectories drift apart (see the note
    # above), but both must converge to the same volume fraction and a
    # comparable compliance.
    @test result.areas[end] ≈ ref_area[end] atol = 1e-2
    @test result.objectives[end] ≈ ref_compliance[end] rtol = 1e-2
end
